### ISSUE TITLE
Add door connections to recast level.

### ISSUE THREAD

**Issue by mitm001** [MeFisto94/jme3-recast4j-demo#11]
Need to add door connections to geometry in recast level through blender. 

Either by adding a material or separating the transition into a separate object and adding user data.

**Comment by mitm001** [comment]
Completed.

**Comment by mitm001** [comment]
Added link.
[6c19469](https://github.com/MeFisto94/jme3-recast4j-demo/commit/6c19469f1162322593947052c8564088a44c4e79)

**Comment by MeFisto94** [comment]
This can be closed as well?

**Comment by mitm001** [comment]
If you approve of the method used to do the searching for traversable polys. 

```
        /**
         * Creating doors in blender with their origin at (0,0,0) is required.
         * The findPolysAroundCircle method in MouseEventControl uses the doors 
         * origin to localize the search for door polys so doors must be moved 
         * into their final position. If you apply location in blender, then 
         * findPolysAroundCircle would start the search from (0,0,0).
         */
```
I use the doors root
```
skelControl.getAttachmentsNode("Root").attachChild(collisionNode);
```
for doing the searches.

[NavState.java#L248](https://github.com/MeFisto94/jme3-recast4j-demo/blob/65f39b7104dbb4b171745b46619017cfd1a5c001/src/main/java/com/jme3/recast4j/demo/states/NavState.java#L248)

and had trouble with the gltf loader so did this crap to make it work. Which really limits its use.

[GltfUserDataLoader.java#L52](https://github.com/MeFisto94/jme3-recast4j-demo/blob/52af8a0e1a9b26f03f326a9df8d3dd773a686f25/src/main/java/com/jme3/recast4j/demo/GltfUserDataLoader.java#L52)

**Comment by mitm001** [comment]
The root bones base is on the floor so thats why I went that route. The searches are only done in X, Y so by using root base, which is at the side of the door, you can do a search based off the width of the door.

This allows for times when there are double doors and one is closed. Path will only find the polys in the doors width that is open.

**Comment by MeFisto94** [comment]
I'll take a look, but this GltfUserDataLoader is "expected", we're also having this in Monake, but probably in a generic version. Maybe we can make this upstream in the engine and a bit configurable?

I'll comment on the rest later, though note that for future additions a pullrequest would've been easier, as we could then simply add in-line comments and others.

**Comment by MeFisto94** [comment]
Closed in favor of https://github.com/MeFisto94/jme3-recast4j/issues/2
