### ISSUE TITLE
Fix All or None to toggle checkboxes in the Crowd panel.

### ISSUE THREAD

**Issue by mitm001** [MeFisto94/jme3-recast4j-demo#16]
Descript says it all.

**Comment by mitm001** [comment]
Link to commit.
[1a3c3fe4](https://github.com/MeFisto94/jme3-recast4j-demo/commit/1a3c3fe4ab6886e0038e3864fff17b8ce6f44e05)

**Comment by MeFisto94** [comment]
So then I can close this?

**Comment by mitm001** [comment]
Yep.
